apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: loki-gateway
  namespace: observability
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: loki.maelkloud.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: loki-cert
            kind: Secret
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: loki-route
  namespace: observability
spec:
  parentRefs:
    - name: loki-gateway
  hostnames:
    - loki.maelkloud.com
  rules:
    - backendRefs:
        - name: loki
          port: 3100
