apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
spec:
  secretName: keycloak-cert
  duration: 2160h
  renewBefore: 360h
  dnsNames:
  - keycloak.maelkloud.com
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer
