apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: keycloak-route
  namespace: keycloak
spec:
  parentRefs:
    - name: main-gateway
      namespace: istio-system
  hostnames:
    - keycloak.maelkloud.com
  rules:
    - backendRefs:
        - name: keycloak-keycloak-keycloakx-http
          port: 80
