apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: monitoring
spec:
  limits:
    - default:
        memory: "2Gi"
        cpu: "1000m"
      defaultRequest:
        memory: "512Mi"
        cpu: "200m"
      type: Container
