apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: observability
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 8Gi
    limits.cpu: "12"
    limits.memory: 16Gi
    persistentvolumeclaims: "12"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: observability
spec:
  limits:
    - default:
        memory: "1Gi"
        cpu: "500m"
      defaultRequest:
        memory: "256Mi"
        cpu: "200m"
      type: Container
