---
# Kyverno Policy to convert Istio Gateway API LoadBalancer services to ClusterIP
# This ensures no LoadBalancer services are created for Gateway API gateways
kind: ClusterPolicy
apiVersion: kyverno.io/v1
metadata:
  name: gateway-service-clusterip
  annotations:
    policies.kyverno.io/title: "Convert Gateway API LoadBalancer Services to ClusterIP"
    policies.kyverno.io/category: "Best Practices"
    policies.kyverno.io/severity: "medium"
    policies.kyverno.io/subject: "Service"
    policies.kyverno.io/description: >-
      Automatically converts LoadBalancer services created by Istio Gateway API
      to ClusterIP type. This prevents the creation of external LoadBalancer
      services when using Gateway API with Istio.
spec:
  rules:
  - name: convert-gateway-loadbalancer-to-clusterip
    match:
      any:
      - resources:
          kinds:
          - Service
    preconditions:
      all:
      - key: "{{ request.object.spec.type }}"
        operator: Equals
        value: LoadBalancer
      - key: "{{ request.object.metadata.labels.\"gateway.istio.io/managed\" }}"
        operator: Equals
        value: "istio.io-gateway-controller"
      mutate:
        patchStrategicMerge:
          spec:
            type: ClusterIP
            # Remove any external IPs that might have been assigned
            externalIPs: null
            # Remove loadBalancerIP if present (deprecated but may exist)
            loadBalancerIP: null
