apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 5m
  path: ./platform/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: mkloudlab
    namespace: flux-system
  targetNamespace: external-secrets
  wait: true
  timeout: 5m
