apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 5m
  path: ./platform/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: mkloudlab
    namespace: flux-system
  # wait: false so cert-controller pod 1/2 does not block this Kustomization
  wait: false
  timeout: 5m
