# Flux HelmRelease for External Secrets Operator
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 5m
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 0.9.11
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 1h
  values:
    installCRDs: true
    webhook:
      port: 9443
    certManager:
      enabled: true
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      seccompProfile:
        type: RuntimeDefault
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    serviceMonitor:
      enabled: true
    metrics:
      serviceMonitor:
        enabled: true
    replicaCount: 2
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - external-secrets
            topologyKey: kubernetes.io/hostname
  targetNamespace: external-secrets-system
  install:
    createNamespace: true
