# Flux HelmRelease for Istio
# Istio is deployed as part of the core platform infrastructure

---
# Istio Base Chart (CRDs and cluster-scoped resources)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: 1.28.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

---
# Istio Control Plane (istiod)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: istiod
      version: 1.28.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1h
  dependsOn:
    - name: istio-base
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Gateway API support
    pilot:
      env:
        PILOT_ENABLE_GATEWAY_API: "true"
        PILOT_ENABLE_GATEWAY_API_STATUS: "true"
        PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER: "true"

    # Resource limits
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
      limits:
        cpu: 2000m
        memory: 4096Mi

    # Enable telemetry
    meshConfig:
      accessLogFile: /dev/stdout
      defaultConfig:
        tracing:
          zipkin:
            address: alloy.observability.svc.cluster.local:9411
