# Flux HelmRelease for Keycloak (Official Keycloak Helm Chart)
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.keycloak.org
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: 26.4.5
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: flux-system
      interval: 1h
  values:
    # Image configuration
    image:
      registry: docker.io
      repository: keycloak/keycloak
      tag: "26.4.5"
      imagePullPolicy: Always
      command: "/opt/keycloak/bin/kc.sh"
    
    # Replica count
    replicaCount: 1
    
    # Security Context
    podSecurityContext:
      fsGroup: 1001
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 1001
      readOnlyRootFilesystem: false
      capabilities:
        drop:
          - ALL
    
    # Keycloak Configuration
    keycloak:
      adminUser: admin
      adminPassword: "Keycloak123!"
      hostnameStrict: false
      httpEnabled: true
      httpPort: 8080
      production: false
      extraArgs: []
    
    # Database Configuration - Use embedded PostgreSQL
    database:
      type: postgres
      name: keycloak
      username: keycloak
      password: "Keycloak123!"
    
    # Embedded PostgreSQL
    postgres:
      enabled: true
      auth:
        database: "keycloak"
        username: ""
        password: ""
    
    # Service configuration
    service:
      type: ClusterIP
      httpPort: 8080
      httpsPort: 8443
      httpTargetPort: 8080
      httpsTargetPort: 8443
    
    # Ingress disabled - using Gateway API
    ingress:
      enabled: false
    
    # Persistence
    persistence:
      enabled: true
      storageClass: local-path
      size: 1Gi
      accessModes:
        - ReadWriteOnce
    
    # Probes
    livenessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
    
    readinessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    
    startupProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 60
    
    # Resources
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    
    # Service Account
    serviceAccount:
      create: true
      automountServiceAccountToken: false
    
    # Init Containers
    initContainers:
      waitForPostgres:
        image: "postgres:17.6"
  targetNamespace: keycloak
  install:
    createNamespace: true
