# Flux HelmRelease for Keycloak (Codecentric Keycloak Helm Chart)
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: codecentric
  namespace: flux-system
spec:
  interval: 1h
  url: https://codecentric.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: 18.10.0
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
      interval: 1h
  values:
    # Image configuration
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.4.5"
      pullPolicy: IfNotPresent

    # Replica count
    replicaCount: 1

    # Keycloak Configuration
    extraEnv: |
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_HOSTNAME_STRICT
        value: "false"
      - name: KC_DB
        value: "postgres"
      - name: KC_DB_URL_HOST
        value: "postgresql"
      - name: KC_DB_URL_DATABASE
        value: "keycloak"
      - name: KC_DB_USERNAME
        value: "keycloak"
      - name: KC_DB_PASSWORD
        value: "Keycloak123!"
      - name: KEYCLOAK_ADMIN
        value: "admin"
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: "Keycloak123!"

    # Command
    command:
      - "/opt/keycloak/bin/kc.sh"
      - "start"
      - "--http-enabled=true"
      - "--hostname-strict=false"

    # Service configuration
    service:
      type: ClusterIP
      httpPort: 8080

    # Ingress disabled - using Gateway API
    ingress:
      enabled: false

    # Persistence
    persistence:
      enabled: true
      storageClass: local-path
      size: 1Gi
      accessMode: ReadWriteOnce

    # Resources
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

    # Security Context
    podSecurityContext:
      fsGroup: 1001
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 1001
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  targetNamespace: keycloak
  install:
    createNamespace: true
