# Flux HelmRelease for Kyverno
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1h
  url: https://kyverno.github.io/kyverno
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: 3.5.2
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 1h
  values:
    replicaCount: 3
    image:
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
    serviceMonitor:
      enabled: true
    metricsConfig:
      enabled: true
    webhookTimeoutSeconds: 10
    priorityClassName: system-cluster-critical
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
    crds:
      install: true
  targetNamespace: kyverno
  install:
    createNamespace: true
