apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 5m
  path: ./platform/observability/loki
  prune: true
  sourceRef:
    kind: GitRepository
    name: mkloudlab
    namespace: flux-system
  targetNamespace: observability
  wait: true
  timeout: 5m
