# Flux HelmRelease for Loki Stack
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: 2.9.11
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
  values:
    loki:
      enabled: true
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi
      podSecurityContext:
        fsGroup: 10001
        runAsUser: 10001
        runAsNonRoot: true
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: false
      config:
        auth_enabled: false
        server:
          http_listen_port: 3100
        ingester:
          lifecycler:
            address: 127.0.0.1
            ring:
              kvstore:
                store: inmemory
              replication_factor: 1
            final_sleep: 0s
          chunk_idle_period: 5m
          chunk_retain_period: 30s
        schema_config:
          configs:
            - from: 2020-10-24
              store: boltdb-shipper
              object_store: filesystem
              schema: v11
              index:
                prefix: index_
                period: 24h
        storage_config:
          boltdb_shipper:
            active_index_directory: /loki/boltdb-shipper-active
            cache_location: /loki/boltdb-shipper-cache
            shared_store: filesystem
          filesystem:
            directory: /loki/chunks
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
    promtail:
      enabled: true
      config:
        clients:
          - url: http://loki:3100/loki/api/v1/push
        scrape_configs:
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_controller_name]
                regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                action: replace
                target_label: __tmp_controller_name
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_label_app, __tmp_controller_name, __meta_kubernetes_pod_name]
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: app
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance, __meta_kubernetes_pod_label_instance]
                regex: (.+)
                target_label: instance
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component, __meta_kubernetes_pod_label_component]
                regex: (.+)
                target_label: component
              - action: replace
                source_labels: [__meta_kubernetes_pod_node_name]
                target_label: node_name
              - action: replace
                source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - action: replace
                source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - action: replace
                source_labels: [__meta_kubernetes_pod_container_name]
                target_label: container
              - action: replace
                replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
                target_label: __path__
    grafana:
      enabled: true
      adminPassword: admin
      persistence:
        enabled: true
        storageClass: local-path
        size: 1Gi
      grafana.ini:
        server:
          domain: loki.maelkloud.com
        auth:
          disable_login_form: false
        auth.anonymous:
          enabled: false
      service:
        type: ClusterIP
        port: 80
  targetNamespace: logging
  install:
    createNamespace: true

