apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: operator
      version: "6.0.4"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
  targetNamespace: minio
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    operator:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
