# Flux Kustomization for MinIO
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 5m
  path: ./platform/storage/minio
  prune: true
  wait: false
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: mkloudlab
  dependsOn:
    - name: networking-config
