# Flux Kustomization for Prometheus & Grafana
# Note: Excludes ArgoCD Application manifests
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 5m
  path: ./platform/observability/prometheus-grafana
  prune: true
  sourceRef:
    kind: GitRepository
    name: mkloudlab
    namespace: flux-system
  targetNamespace: monitoring
  wait: true
  timeout: 5m
  # ArgoCD Application manifests excluded via kustomization.yaml

