apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking
  namespace: flux-system
spec:
  interval: 10m
  path: "./platform/networking"
  prune: true
  sourceRef:
    kind: GitRepository
    name: mkloudlab
    namespace: flux-system
  # Dependencies commented out - kustomizations are named differently in cluster
  # dependsOn:
  #   - name: kyverno
  #   - name: external-secrets
