# Flux Kustomization for NeuVector (namespace + CRD and core HelmReleases)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: neuvector
  namespace: flux-system
spec:
  interval: 5m
  path: ./platform/neuvector
  prune: true
  sourceRef:
    kind: GitRepository
    name: mkloudlab
    namespace: flux-system
