apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarqube
  namespace: flux-system
spec:
  interval: 5m
  path: ./services/sonarqube
  prune: true
  sourceRef:
    kind: GitRepository
    name: mkloudlab
    namespace: flux-system
  targetNamespace: sonarqube
  wait: true
  timeout: 5m
