# Flux HelmRelease for Grafana Tempo
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-tempo
  namespace: flux-system
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo
      version: 1.24.0
      sourceRef:
        kind: HelmRepository
        name: grafana-tempo
        namespace: flux-system
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: tempo-values
      valuesKey: values.yaml
      optional: true
  values:
    # Tempo configuration for Helm chart v1.24.0
    # Note: Configuration structure matches the Helm chart values schema
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
      wal:
        path: /var/tempo/wal
    server:
      http_listen_port: 3200
      log_level: info
    auth_enabled: false
    ingester:
      replicas: 1
      persistence:
        enabled: true
        size: 20Gi
        storageClassName: local-path
    compactor:
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: local-path
    queryFrontend:
      replicas: 1
    querier:
      replicas: 1
    metricsGenerator:
      enabled: false
    tempoGateway:
      enabled: false
    serviceMonitor:
      enabled: true
    traces:
      jaeger:
        thriftHttp:
          enabled: false
      zipkin:
        enabled: false
      otlp:
        grpc:
          enabled: true
          receiverProtocol: grpc
          listenAddress: 0.0.0.0
        http:
          enabled: true
          listenAddress: 0.0.0.0
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  targetNamespace: observability
  install:
    createNamespace: true
