apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana-alloy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces", "nodes", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy
subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: observability
---
apiVersion: v1
kind: Service
metadata:
  name: alloy-gateway
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana-alloy
spec:
  selector:
    app.kubernetes.io/name: grafana-alloy
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: http-metrics
      port: 12345
      targetPort: 12345
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy-agent
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana-alloy
    app.kubernetes.io/component: agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-alloy
      app.kubernetes.io/component: agent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-alloy
        app.kubernetes.io/component: agent
    spec:
      serviceAccountName: alloy
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: alloy
          image: grafana/alloy:latest
          imagePullPolicy: Always
          workingDir: /tmp/alloy-data
          args:
            - "run"
            - "/etc/alloy/alloy.river"
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 12345
              name: http-metrics
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: data
              mountPath: /tmp/alloy-data
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 12345
            initialDelaySeconds: 10
            periodSeconds: 15
      volumes:
        - name: config
          configMap:
            name: alloy-config
        - name: data
          emptyDir: {}
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: alloy-agent
  namespace: observability
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-alloy
      app.kubernetes.io/component: agent

