# Flux HelmRelease for NeuVector core (manager, controller, enforcer, scanner)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neuvector
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: neuvector-crd
  chart:
    spec:
      chart: core
      version: "2.8.10"
      sourceRef:
        kind: HelmRepository
        name: neuvector
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
  targetNamespace: neuvector
  values:
    manager:
      # Disable TLS on manager so Istio Gateway can terminate TLS and forward HTTP
      env:
        ssl: false
      svc:
        type: ClusterIP
