# Flux HelmRelease for NeuVector CRD chart (install before core)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neuvector-crd
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: crd
      version: "2.8.10"
      sourceRef:
        kind: HelmRepository
        name: neuvector
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
  targetNamespace: neuvector
