apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.14.9"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: networking
  targetNamespace: networking
  install:
    createNamespace: true
  values:
    controller:
      logLevel: info
    speaker:
      logLevel: info
