# Flux HelmRelease for MinIO
apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
    istio-injection: enabled
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: 17.0.21
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1h
  values:
    # Authentication
    auth:
      rootUser: admin
      rootPassword: minio123  # TODO: Move to external secret in production

    # Deployment mode (standalone for homelab, distributed for production)
    mode: standalone

    # Persistence
    persistence:
      enabled: true
      storageClass: local-path
      size: 50Gi

    # Resources
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi

    # Security context
    podSecurityContext:
      enabled: true
      fsGroup: 1001
      runAsUser: 1001
      runAsNonRoot: true

    containerSecurityContext:
      enabled: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1001

    # Service configuration
    service:
      type: ClusterIP
      ports:
        api: 9000
        console: 9001

    # Ingress - disabled, using Gateway API
    ingress:
      enabled: false

    # Enable MinIO Console (web UI)
    consoleService:
      type: ClusterIP
      ports:
        http: 9001

    # Default buckets to create
    defaultBuckets: "backups,logs,artifacts,velero"

    # Metrics (for Prometheus)
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: minio
