apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-cleanup-controller
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-cleanup-controller
subjects:
  - kind: ServiceAccount
    name: kyverno-cleanup-controller
    namespace: kyverno
roleRef:
  kind: ClusterRole
  name: kyverno-cleanup-controller
  apiGroup: rbac.authorization.k8s.io
