---
# TLS Certificate for MinIO
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-cert
  namespace: monitoring
spec:
  secretName: minio-cert
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - minio.maelkloud.com
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer
