# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION         = "2"
ENV['VAGRANT_NO_PARALLEL']  = 'yes'

VAGRANT_BOX         = "bento/ubuntu-24.04"
VAGRANT_BOX_VERSION = "202502.21.0"
CPUS_MASTER_NODE    = 10
CPUS_WORKER_NODE    = 10
MEMORY_MASTER_NODE  = 16384
MEMORY_WORKER_NODE  = 16384
WORKER_NODES_COUNT  = (ENV['WORKER_COUNT'] || 3).to_i
NETWORK_PREFIX      = "172.16.16"


Vagrant.configure(VAGRANT_API_VERSION) do |config|

  config.vm.box               = VAGRANT_BOX
  config.vm.box_check_update  = false
  config.vm.box_version       = VAGRANT_BOX_VERSION
  config.vm.boot_timeout       = 180

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "kcontroller" do |node|

    node.vm.hostname = "kcontroller.example.com"
    node.vm.network "private_network", ip: "#{NETWORK_PREFIX}.100"
    node.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    node.vm.network "forwarded_port", guest: 6443, host: 6443, auto_correct: true

    node.vm.provider :virtualbox do |v|
      v.name    = "kcontroller"
      v.memory  = MEMORY_MASTER_NODE
      v.cpus    = CPUS_MASTER_NODE
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["storagectl", :id, "--name", "VirtIO Controller", "--hostiocache", "on"]
    end

    node.vm.provider :libvirt do |v|
      v.memory  = MEMORY_MASTER_NODE
      v.nested  = true
      v.cpus    = CPUS_MASTER_NODE
    end

    node.vm.provision "shell", path: "bootstrap_kcontroller.sh"

  end


  # Kubernetes Worker Nodes
  (1..WORKER_NODES_COUNT).each do |i|

    config.vm.define "knode#{i}" do |node|

      node.vm.hostname = "knode#{i}.example.com"
      node.vm.network "private_network", ip: "#{NETWORK_PREFIX}.10#{i}"

      node.vm.provider :virtualbox do |v|
        v.name    = "knode#{i}"
        v.memory  = MEMORY_WORKER_NODE
        v.cpus    = CPUS_WORKER_NODE
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.customize ["modifyvm", :id, "--ioapic", "on"]
        v.customize ["storagectl", :id, "--name", "VirtIO Controller", "--hostiocache", "on"]
      end

      node.vm.provider :libvirt do |v|
        v.memory  = MEMORY_WORKER_NODE
        v.nested  = true
        v.cpus    = CPUS_WORKER_NODE
      end

      node.vm.provision "shell", path: "bootstrap_knode.sh"

    end

  end

end
