---
# Automatic HTTP to HTTPS redirect for all services
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-redirect
  namespace: istio-system
spec:
  parentRefs:
    - name: main-gateway
      namespace: istio-system
      sectionName: http  # Only apply to HTTP listener
  hostnames:
    - "*.maelkloud.com"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
