apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarqube-cert
  namespace: sonarqube
spec:
  secretName: sonarqube-cert
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - sonarqube.maelkloud.com
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer
