# ExternalSecrets for SonarQube - syncs secrets from secrets-store namespace
---
# SonarQube Admin Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-admin
  namespace: sonarqube
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-store
    kind: SecretStore
  target:
    name: sonarqube-admin
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: sonarqube-admin
      property: username
  - secretKey: password
    remoteRef:
      key: sonarqube-admin
      property: password
  - secretKey: currentPassword
    remoteRef:
      key: sonarqube-admin
      property: current-password
---
# SonarQube PostgreSQL Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-postgresql
  namespace: sonarqube
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-store
    kind: SecretStore
  target:
    name: sonarqube-postgresql
    creationPolicy: Owner
  data:
  - secretKey: postgres-user
    remoteRef:
      key: sonarqube-postgresql
      property: postgres-user
  - secretKey: postgres-password
    remoteRef:
      key: sonarqube-postgresql
      property: postgres-password
  - secretKey: postgres-db
    remoteRef:
      key: sonarqube-postgresql
      property: postgres-db
---
# SonarQube Monitoring Passcode
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-monitoring
  namespace: sonarqube
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-store
    kind: SecretStore
  target:
    name: sonarqube-monitoring
    creationPolicy: Owner
  data:
  - secretKey: passcode
    remoteRef:
      key: sonarqube-monitoring
      property: passcode
