# PostgreSQL StatefulSet for SonarQube - SECURITY HARDENED
# NOTE: Secrets are managed by External Secrets Operator
# See services/sonarqube/external-secrets.yaml for secret configuration
# Actual secret values are stored in secrets-store namespace
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube-postgresql
  namespace: sonarqube
  labels:
    app: sonarqube-postgresql
spec:
  serviceName: sonarqube-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-postgresql
  template:
    metadata:
      labels:
        app: sonarqube-postgresql
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      # Security Context - Pod Level
      securityContext:
        runAsNonRoot: true
        runAsUser: 999  # postgres user
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault

      # Init container to fix permissions on existing data
      initContainers:
      - name: fix-permissions
        image: postgres:15-alpine
        command:
        - sh
        - -c
        - |
            chown -R 999:999 /var/lib/postgresql/data || true
            chown -R 999:999 /var/run/postgresql || true
            chown -R 999:999 /tmp || true
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: tmp
          mountPath: /tmp
        - name: run
          mountPath: /var/run/postgresql
        securityContext:
          runAsUser: 0  # Need root to chown
          runAsNonRoot: false

      containers:
      - name: postgresql
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent

        # Security Context - Container Level
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false  # PostgreSQL needs write access
          seccompProfile:
            type: RuntimeDefault

        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP

        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: sonarqube-postgresql
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-postgresql
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: sonarqube-postgresql
              key: postgres-db
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        # Security: SSL/TLS configuration
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "scram-sha-256"  # Use strong password hashing
        - name: POSTGRES_INITDB_ARGS
          value: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"

        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: tmp
          mountPath: /tmp
        - name: run
          mountPath: /var/run/postgresql

        # Resource Limits - REQUIRED
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi

        # Health Probes
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U sonarUser
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U sonarUser -d sonarDB
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U sonarUser -d sonarDB
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30

      volumes:
      - name: tmp
        emptyDir: {}
      - name: run
        emptyDir: {}

  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: sonarqube-postgresql
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgresql
  namespace: sonarqube
  labels:
    app: sonarqube-postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
  selector:
    app: sonarqube-postgresql
  # Session affinity for sticky connections
  sessionAffinity: ClientIP
