# SecretStore for SonarQube - points to secrets-store namespace
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secrets-store
  namespace: sonarqube
spec:
  provider:
    kubernetes:
      remoteNamespace: secrets-store
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
