apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: v3.4.1
    chart: kyverno
    helm:
      values: |
        replicaCount: 3
        image:
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        serviceMonitor:
          enabled: true
        metricsConfig:
          enabled: true
        webhookTimeoutSeconds: 10
        priorityClassName: system-cluster-critical
        tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Exists"
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - kyverno
                  topologyKey: "kubernetes.io/hostname"
        webhookTimeoutSeconds: 10
        priorityClassName: system-cluster-critical
        tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Exists"
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - kyverno
                  topologyKey: "kubernetes.io/hostname"
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
