apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: "1.78.x"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # OAuth credentials stored in Kubernetes Secret (not in git!)
    # Secret created separately - see oauth-secret.yaml (NOT committed)
    oauth:
      clientId:
        valueFrom:
          secretKeyRef:
            name: tailscale-operator-oauth
            key: client-id
      clientSecret:
        valueFrom:
          secretKeyRef:
            name: tailscale-operator-oauth
            key: client-secret

    # Proxy configuration
    operatorConfig:
      # Default hostname prefix for services
      hostname: "mkloud"

      # Enable debug logging
      logging: "info"

      # Accept DNS routes from other Tailscale nodes
      acceptRoutes: true

    # API server proxy for improved performance
    apiServerProxyConfig:
      mode: "true"

    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
