apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    name: tailscale
    toolkit.fluxcd.io/tenant: platform
    # Disable Istio sidecar injection - Tailscale proxy needs direct network access
    sidecar.istio.io/inject: "false"
