apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
type: Opaque
stringData:
  OAUTH_CLIENT_ID: grafana
  OAUTH_CLIENT_SECRET: e930a60d-c0e7-43ce-812f-1c31fa861426
