---
# TLS Certificate for Jenkins
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-cert
  namespace: jenkins
spec:
  secretName: jenkins-cert
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - jenkins.maelkloud.com
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer