apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "1.14.3"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: networking
  targetNamespace: networking
  install:
    createNamespace: true
  values:
    provider: cloudflare
    sources:
      - service
      - ingress
      - istio-gateway
      - istio-virtualservice
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token-secret
            key: api-token
    domainFilters:
      - maelkloud.com
    policy: sync
    txtOwnerId: mkloudlab
