# Flux HelmRelease for Keycloak (Codecentric KeycloakX Helm Chart)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloakx
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
      interval: 1h
  targetNamespace: keycloak
  install:
    createNamespace: true
  values:
    # Admin Credentials
    username: admin
    password: "REDACTED"

    # Service Configuration
    service:
      type: ClusterIP
      port: 8080

    # Ingress Configuration (using Gateway API separately)
    ingress:
      enabled: false

    # Database Configuration
    # Note: Codecentric chart expects external database or separate PostgreSQL deployment
    # Configure environment variables for database connection
    # Using YAML literal block scalar format (the chart expects a string that will be parsed as YAML)
    extraEnv: |
      - name: KC_DB
        value: postgres
      - name: KC_DB_URL_HOST
        value: keycloak-postgresql
      - name: KC_DB_URL_DATABASE
        value: keycloak
      - name: KC_DB_USERNAME
        value: keycloak
      - name: KC_DB_PASSWORD
        value: REDACTED
      - name: KC_PROXY
        value: edge
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_HOSTNAME_STRICT
        value: "false"
      - name: KC_HOSTNAME_STRICT_BACKCHANNEL
        value: "false"

    # Cache Configuration
    cache:
      stack: local

    # HTTP Configuration
    http:
      relativePath: "/"
