# PostgreSQL StatefulSet for Keycloak - SECURITY HARDENED
# NOTE: Passwords should be managed via External Secrets Operator in production

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql
  namespace: keycloak
  labels:
    app: keycloak-postgresql
type: Opaque
stringData:
  # TODO: Use External Secrets Operator or Sealed Secrets
  # Generate strong passwords: openssl rand -base64 32
  postgres-password: "CHANGE_ME_USE_STRONG_PASSWORD"
  postgres-user: "keycloak"
  postgres-db: "keycloak"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-postgresql
  namespace: keycloak
  labels:
    app: keycloak-postgresql
spec:
  serviceName: keycloak-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgresql
  template:
    metadata:
      labels:
        app: keycloak-postgresql
    spec:
      # Security Context - Pod Level
      securityContext:
        runAsNonRoot: true
        runAsUser: 999  # postgres user
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: postgresql
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent

        # Security Context - Container Level
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false  # PostgreSQL needs write access
          seccompProfile:
            type: RuntimeDefault

        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP

        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-postgresql
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-postgresql
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: keycloak-postgresql
              key: postgres-db
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        # Security: SSL/TLS configuration
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "scram-sha-256"  # Use strong password hashing
        - name: POSTGRES_INITDB_ARGS
          value: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"

        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: tmp
          mountPath: /tmp
        - name: run
          mountPath: /var/run/postgresql

        # Resource Limits - REQUIRED
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi

        # Health Probes
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U keycloak -d keycloak
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6

        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U keycloak -d keycloak
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U keycloak -d keycloak
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30

      volumes:
      - name: tmp
        emptyDir: {}
      - name: run
        emptyDir: {}

  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: keycloak-postgresql
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgresql
  namespace: keycloak
  labels:
    app: keycloak-postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
  selector:
    app: keycloak-postgresql
  # Session affinity for sticky connections
  sessionAffinity: ClientIP
