# Comprehensive RBAC Policies for Enhanced Security
# Note: ArgoCD resources removed - using Flux for GitOps

# Service Account for Security operations
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-scanner
  namespace: kyverno
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: scanner
---
# ClusterRole for Security Scanner
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-scanner-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kyverno.io"]
    resources: ["clusterpolicies", "policies"]
    verbs: ["get", "list", "watch"]
---
# ClusterRoleBinding for Security Scanner
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-scanner-binding
subjects:
  - kind: ServiceAccount
    name: security-scanner
    namespace: kyverno
roleRef:
  kind: ClusterRole
  name: security-scanner-role
  apiGroup: rbac.authorization.k8s.io
