apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: observability
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    persistentvolumeclaims: "4"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: sonarqube
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: monitoring
spec:
  limits:
    - default:
        memory: "2Gi"
        cpu: "1000m"
      defaultRequest:
        memory: "512Mi"
        cpu: "200m"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: observability
spec:
  limits:
    - default:
        memory: "1Gi"
        cpu: "500m"
      defaultRequest:
        memory: "256Mi"
        cpu: "200m"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: sonarqube
spec:
  limits:
    - default:
        memory: "2Gi"
        cpu: "1000m"
      defaultRequest:
        memory: "512Mi"
        cpu: "250m"
      type: Container
