apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-cloudflare
spec:
  acme:
    email: xmaeltht@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-cloudflare-account-key
    solvers:
      - dns01:
          cloudflare:
            email: xmaeltht@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
# Note: Certificate resources for specific services should be created
# in their respective namespaces as needed. Examples:
# - Keycloak: services/keycloak/keycloak-cert.yaml
# - SonarQube: services/sonarqube/sonar-cert.yaml
# - Prometheus/Grafana: platform/observability/prometheus-grafana/certificates.yaml
