apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: tempo-gateway
  namespace: observability
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: tempo.maelkloud.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: tempo-cert
            kind: Secret
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: tempo-route
  namespace: observability
spec:
  parentRefs:
    - name: tempo-gateway
  hostnames:
    - tempo.maelkloud.com
  rules:
    - backendRefs:
        - name: tempo
          port: 3200
