# Application manifest for SonarQube Gateway and Certificate
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/xmaeltht/mkloudlab.git"
    path: services/sonarqube
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
