# Istio VirtualService Template
# This template shows how to create VirtualService for applications
# Replace the placeholders with your actual values

---
# Gateway for HTTPS traffic
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: "{{APP_NAME}}-gateway"
  namespace: "{{NAMESPACE}}"
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "{{DOMAIN}}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "{{APP_NAME}}-cert"
            kind: Secret

---
# Certificate for the domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{APP_NAME}}-cert"
  namespace: "{{NAMESPACE}}"
spec:
  secretName: "{{APP_NAME}}-cert"
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - "{{DOMAIN}}"
  issuerRef:
    name: letsencrypt-dns-cloudflare  # Use DNS-01 for better reliability
    kind: ClusterIssuer

---
# VirtualService for traffic routing
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "{{APP_NAME}}-vs"
  namespace: "{{NAMESPACE}}"
spec:
  hosts:
    - "{{DOMAIN}}"
  gateways:
    - "{{NAMESPACE}}/{{APP_NAME}}-gateway"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: "{{SERVICE_NAME}}"
            port:
              number: "{{SERVICE_PORT}}"

---
# Service (if not already exists)
apiVersion: v1
kind: Service
metadata:
  name: "{{SERVICE_NAME}}"
  namespace: "{{NAMESPACE}}"
spec:
  selector:
    app: "{{APP_NAME}}"
  ports:
    - name: http
      protocol: TCP
      port: "{{SERVICE_PORT}}"
      targetPort: "{{TARGET_PORT}}"
  type: ClusterIP
